### PR TITLE
IOPS-927 Add license checker

### PR DESCRIPTION
**Pull request by msobo1**
Check dependency licenses - PR test

### CODE REVIEW

**Review by ldanilina — COMMENTED** [review]
LGTM.
A suggestion: can we also configure the command to run? or at least the format and the output path.
Also, the action name should probably mention that it's npm license-checker to create a diff as a PR (something like dolby-io-internal/npm-license-checker-pr), the name seems ambiguous.

**Review by aravind-raveendran — APPROVED** [review]

**Comment by CasperMok** [comment]
> LGTM. A suggestion: can we also configure the command to run? or at least the format and the output path. Also, the action name should probably mention that it's npm license-checker to create a diff as a PR (something like dolby-io-internal/npm-license-checker-pr), the name seems ambiguous.

@msobo1 Any response to this?

**Comment by msobo1** [comment]
> > LGTM. A suggestion: can we also configure the command to run? or at least the format and the output path. Also, the action name should probably mention that it's npm license-checker to create a diff as a PR (something like dolby-io-internal/npm-license-checker-pr), the name seems ambiguous.
> 
> @msobo1 Any response to this?

Yes, we can do additional configuration of the command. New name is also fine for me.

**Review by ldanilina — APPROVED** [review]

**Review by CasperMok — DISMISSED** [review]

**Comment by ldanilina** [comment]
rebased in order to verify commit

**Review by ldanilina — APPROVED** [review]

**Review by CasperMok — APPROVED** [review]

**Pull request merged**
